version: "3.7"

services:
  mongo:
    image: mongo
    container_name: movies-catalog-database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    container_name: movies-catalog-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongo
